spec:
  inputs:
    source-env:
      description: "Source environment"
      default: "dev"
      options: ["dev", "sta", "prod"]
    target-env:
      description: "Target environment"
      default: "sta"
      options: ["dev", "sta", "prod"]
    promote-containers:
      description: "Promote container tag"
      type: boolean
      default: true
    promote-configmaps:
      description: "Also promote configmap settings"
      type: boolean
      default: false
    promote-settings:
      description: "Also promote workload settings"
      type: boolean
      default: false
    commit-message:
      default: "workload promotion"
---
default:
  image: ubuntu:latest

promote:
  variables:
    REPO: "git@gitlab.com:<GIT_ORGANIZATION_NAME>/<WL_GITOPS_REPO_NAME>.git"
    ARGO_NAMESPACE: wl-<WL_NAME>-build
    ARGO_INSTANCEID: cgdevx
  script: |
    # Download the binary
    set -x
    apt update
    apt install -y curl git jq
    curl -sLO https://github.com/argoproj/argo-workflows/releases/download/v3.5.2/argo-linux-amd64.gz
    gunzip argo-linux-amd64.gz
    chmod +x argo-linux-amd64
    mv ./argo-linux-amd64 /usr/local/bin/argo
    argo version

    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod +x kubectl
    mv kubectl /usr/local/bin/
    kubectl config use-context $(kubectl config get-contexts -o name | head -n 1)

    pwd
    ls -lar
    argo submit .argo/promote-wf.yaml \
      -p repo=${REPO} \
      -p env-path="gitops/environments/envs" \
      -p source-env="$[[ inputs.source-env ]]" \
      -p target-env="$[[ inputs.target-env ]]" \
      -p promote-container=$[[ inputs.promote-containers ]] \
      -p promote-settings=$[[ inputs.promote-settings ]] \
      -p promote-configmaps=$[[ inputs.promote-configmaps ]] \
      -p commit-message=\""$[[ inputs.commit-message ]]"\" \
      --serviceaccount argo-workflow \
      --wait --log

  when: manual
