---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflow-cwft-<WL_NAME>-crb
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-workflow-controller-cluster-template
subjects:
  - kind: ServiceAccount
    name: argo-workflow
    namespace: wl-<WL_NAME>-dev
