---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-admin
  annotations:
    argocd.argoproj.io/sync-wave: '-5'
    workflows.argoproj.io/rbac-rule: "'<WL_NAME>-admins' in groups or 'admins' in groups"
    workflows.argoproj.io/rbac-rule-precedence: '5'
secrets:
  - name: argo-admin
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-admin
  annotations:
    kubernetes.io/service-account.name: argo-admin
    argocd.argoproj.io/sync-wave: "-5"
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-admin-rb
  annotations:
    argocd.argoproj.io/sync-wave: '-5'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-admin
subjects:
  - kind: ServiceAccount
    name: argo-admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-developer
  annotations:
    argocd.argoproj.io/sync-wave: '-5'
    workflows.argoproj.io/rbac-rule: "'<WL_NAME>-developers' in groups or 'developers' in groups"
    workflows.argoproj.io/rbac-rule-precedence: '4'
secrets:
  - name: argo-developer
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-developer
  annotations:
    argocd.argoproj.io/sync-wave: '-5'
    kubernetes.io/service-account.name: argo-developer
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-developer-rb
  annotations:
    argocd.argoproj.io/sync-wave: '-5'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-view
subjects:
  - kind: ServiceAccount
    name: argo-developer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-logreader-rb
  annotations:
    argocd.argoproj.io/sync-wave: '-5'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-logreader
subjects:
- kind: ServiceAccount
  name: argo-admin
  namespace: wl-<WL_NAME>-dev
- kind: ServiceAccount
  name: argo-developer
  namespace: wl-<WL_NAME>-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflow
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    # <K8S_ROLE_MAPPING>: "<CI_IAM_ROLE_RN>"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - watch
      - patch
  - apiGroups:
      - ''
    resources:
      - pods/log
    verbs:
      - get
      - watch
  - apiGroups:
      - ''
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets
      - workflowartifactgctasks
    verbs:
      - list
      - watch
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets/status
      - workflowartifactgctasks/status
    verbs:
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflow
subjects:
  - kind: ServiceAccount
    name: argo-workflow
