---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow-controller-secret-reader
  namespace: wl-<WL_NAME>-dev
rules:
  - apiGroups: ['']
    resources: [secrets]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-controller-secret-reader
  namespace: wl-<WL_NAME>-dev
  annotations:
    argocd.argoproj.io/sync-wave: '0'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflow-controller-secret-reader
subjects:
  - kind: ServiceAccount
    name: argo-workflow-controller
    namespace: argo
