---
# Business settings that will be promoted between environments
apiVersion: v1
kind: ConfigMap
metadata:
  name: <WL_SERVICE_NAME>
  labels: {}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
data: {}

