---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ci-secrets
  namespace: wl-<WL_NAME>-dev
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  target:
    name: ci-secrets
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  dataFrom:
    - extract:
        key: /ci-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: container-registry-auth
  namespace: wl-<WL_NAME>-dev
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  target:
    name: container-registry-auth
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  data:
    - remoteRef:
        key: registry-auth
        property: auth
      secretKey: config.json
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docker-config
  namespace: wl-<WL_NAME>-dev
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{{ .dockerconfig | toString }}'
    name: docker-config
    creationPolicy: Owner
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  data:
    - secretKey: dockerconfig
      remoteRef:
        property: dockerconfig
        key: dockerconfigjson
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: proxy-docker-config
  namespace: wl-<WL_NAME>-dev
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{{ .dockerconfig | toString }}'
    name: proxy-docker-config
    creationPolicy: Owner
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  data:
    - secretKey: dockerconfig
      remoteRef:
        property: dockerconfig
        key: proxy_dockerconfigjson
