---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: <WL_SERVICE_NAME>
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  target:
    name: <WL_SERVICE_NAME>
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-workloads-secret
  refreshInterval: 10s
  dataFrom:
    - extract:
        key: /<WL_NAME>/dev/<WL_SERVICE_NAME>
