---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ci-secrets
  annotations:
    argocd.argoproj.io/sync-wave: '-5'
spec:
  target:
    name: ci-secrets
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  dataFrom:
    - extract:
        key: /ci-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: push-docker-config
  annotations:
    argocd.argoproj.io/sync-wave: '-5'
spec:
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{{ .dockerconfig | toString }}'
    name: push-docker-config
    creationPolicy: Owner
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-workloads-secret 
  refreshInterval: 10s
  data:
    - secretKey: dockerconfig
      remoteRef:
        property: dockerconfig
        key: /<WL_NAME>/push_dockerconfigjson
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: proxy-docker-config
  annotations:
    argocd.argoproj.io/sync-wave: '-5'
spec:
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{{ .dockerconfig | toString }}'
    name: proxy-docker-config
    creationPolicy: Owner
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  data:
    - secretKey: dockerconfig
      remoteRef:
        property: dockerconfig
        key: proxy_dockerconfigjson
