---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-admin
  annotations:
    argocd.argoproj.io/sync-wave: '-5'
    workflows.argoproj.io/rbac-rule: "'<WL_NAME>-admins' in groups"
    workflows.argoproj.io/rbac-rule-precedence: '2'
secrets:
  - name: argo-admin
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-admin
  annotations:
    kubernetes.io/service-account.name: argo-admin
    argocd.argoproj.io/sync-wave: "-5"
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-admin-rb
  annotations:
    argocd.argoproj.io/sync-wave: '-5'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-admin
subjects:
  - kind: ServiceAccount
    name: argo-admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-developer
  annotations:
    argocd.argoproj.io/sync-wave: '-5'
    workflows.argoproj.io/rbac-rule: "'<WL_NAME>-developers' in groups"
    workflows.argoproj.io/rbac-rule-precedence: '1'
secrets:
  - name: argo-developer
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-developer
  annotations:
    argocd.argoproj.io/sync-wave: '-5'
    kubernetes.io/service-account.name: argo-developer
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-developer-rb
  annotations:
    argocd.argoproj.io/sync-wave: '-5'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-view
subjects:
  - kind: ServiceAccount
    name: argo-developer
