---
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
- name: proxy-docker-config
metadata:
  name: argo-workflow
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    # <K8S_ROLE_MAPPING>: "<CI_IAM_ROLE_RN>"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - get
    - watch
    - list
  - apiGroups:
    - ""
    resources:
    - persistentvolumeclaims
    - persistentvolumeclaims/finalizers
    verbs:
    - create
    - update
    - delete
    - get
  - apiGroups:
    - argoproj.io
    resources:
    - workflows
    - workflows/finalizers
    - workflowtasksets
    - workflowtasksets/finalizers
    - workflowartifactgctasks
    verbs:
    - get
    - list
    - watch
    - update
    - patch
    - delete
    - create
  - apiGroups:
    - ''
    resources:
    - pods
    verbs:
        - get
        - watch
        - patch
  - apiGroups:
      - ''
    resources:
      - pods/log
    verbs:
      - get
      - watch
  - apiGroups:
      - ''
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets
      - workflowartifactgctasks
    verbs:
      - list
      - watch
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets/status
      - workflowartifactgctasks/status
    verbs:
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflow
subjects:
  - kind: ServiceAccount
    name: argo-workflow
