---
# Business settings that will be promoted between environments
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <WL_SERVICE_NAME>
spec:
  template:
    spec:
      containers:
        - name: <WL_SERVICE_NAME>-container
          env: []

