---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: promote-wf
  namespace: argo
spec:
  arguments:
    parameters:
      - name: dockerhub-registry-proxy
        value: <REGISTRY_DOCKERHUB_PROXY>
      - name: env-path
        value: ''
      - name: target-env  # path
        value: ''
      - name: source-env  # path
        value: ''
      - name: promote-container  # true/flase
        value: ''
      - name: promote-settings  # true/flase
        value: ''
      - name: promote-configmap  # true/flase
        value: ''
      - name: commit-message
        value: ''
  entrypoint: promote-seq
  imagePullSecrets:
    - name: proxy-docker-config
  onExit: exit-handler
  volumes:
    - name: ssh-key-vol
      secret:
        secretName: ci-secrets
        defaultMode: 256
    - name: kaniko-secret
      secret:
        secretName: proxy-docker-config
        items:
          - key: .dockerconfigjson
            path: config.json
  templates:
    - name: promote-seq
      dag:
        tasks:
          - name: promote
            templateRef:
              name: promote-cwft
              template: promote
              clusterScope: true
    - name: exit-handler
      container:
        image: '{{workflow.parameters.dockerhub-registry-proxy}}/library/alpine'
        imagePullPolicy: IfNotPresent
        command:
          - sh
          - -c
        args:
          - 'echo Promote Workflow execution status: {{workflow.name}} {{workflow.status}}
            {{workflow.duration}}'
