---
# Defines common characteristics between environments
# Kubernetes specific settings, eg resource limits, health checks, persistent volumes, affinity rules, etc.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "<WL_SERVICE_NAME>"
spec:
  template:
    spec:
      containers:
      - name: "<WL_SERVICE_NAME>-container"
        livenessProbe:
          httpGet:
            path: /livez
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 2
          failureThreshold: 3
          timeoutSeconds: 30
        resources:
          limits:
            cpu: 100m
            memory: "256Mi"
          requests:
            cpu: 40m
            memory: "128Mi"