---
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: argocd-common-labels
labels:
  cg-devx.cost-allocation.workload: "<WL_NAME>"
  cg-devx.cost-allocation.cost-center: development
  cg-devx.metadata.owner: "<WL_NAME>-admins:<WL_NAME>-developers"
fieldSpecs:
- path: metadata/labels
  create: true
