---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <WL_SERVICE_NAME>
  annotations: {
    reloader.stakater.com/auto: 'true',
    # <K8S_ROLE_MAPPING>: "<WL_IAM_ROLE_RN>"
    }
  labels: {
    cg-devx.metadata.service: "<WL_SERVICE_NAME>-app"
    # <ADDITIONAL_LABELS>
    }
spec:
  replicas: 1
  selector:
    matchLabels:
      "cg-devx.metadata.service": "<WL_SERVICE_NAME>-app"
  template:
    metadata:
      labels:
        "cg-devx.metadata.service": "<WL_SERVICE_NAME>-app"
    spec:
      serviceAccountName: <WL_SERVICE_NAME>
      imagePullSecrets:
        - name: docker-config-wl
      containers:
        - name: <WL_SERVICE_NAME>-container
          envFrom:
            - configMapRef:
                name: <WL_SERVICE_NAME>
            - secretRef:
                name: <WL_SERVICE_NAME>
          imagePullPolicy: IfNotPresent
          image: <WL_SERVICE_IMAGE>
          livenessProbe:
            httpGet:
              path: /livez
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 30
          ports:
            - name: http
              containerPort: <WL_SERVICE_PORT>
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 40m
              memory: 64Mi
