---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: <WL_SERVICE_NAME>
  labels: {}
  annotations:
    # <K8S_ROLE_MAPPING>: "<WL_IAM_ROLE_RN>"
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: <WL_SERVICE_NAME>
rules:
# example of policy rules
  - apiGroups: [apps]
    resources: [deployments, statefulsets]
    verbs: [get, watch, list]
  - apiGroups: ['']
    resources: [secrets, configmaps]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: <WL_SERVICE_NAME>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: <WL_SERVICE_NAME>
subjects:
  - kind: ServiceAccount
    name: <WL_SERVICE_NAME>
