apiVersion: v1
kind: ServiceAccount
metadata:
  name: <WL_SERVICE_NAME>-sa
  labels: {}
  annotations:
    <K8S_ROLE_MAPPING>: "<WL_IAM_ROLE_RN>"
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "<WL_SERVICE_NAME>-role"
  namespace: "<WL_SERVICE_NAMESPACE>"
rules:
  - apiGroups: []
    resources: []
    verbs: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "<WL_SERVICE_NAME>"
  namespace: "<WL_SERVICE_NAMESPACE>"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "<WL_SERVICE_NAME>-role"
subjects:
  - kind: ServiceAccount
    name: "<WL_SERVICE_NAME>-sa"
    namespace: "<WL_SERVICE_NAMESPACE>"
