apiVersion: v1
kind: Service
metadata:
  name: <WL_SERVICE_NAME>
spec:
  type: ClusterIP
  selector:
    app: "<WL_SERVICE_NAME>-app"
  ports:
    - protocol: TCP
      port: <WL_SERVICE_NAME_PORT>
      targetPort: http
      name: http