---
apiVersion: v1
kind: Service
metadata:
  name: <WL_SERVICE_NAME>
  labels: {
    expose-metrics: 'true'
  }
spec:
  type: ClusterIP
  selector:
    cg-devx.metadata.service: "<WL_SERVICE_NAME>-app"
  ports:
    - protocol: TCP
      port: <WL_SERVICE_PORT>
      targetPort: http
      name: http

